# Generated by Django 4.1.2 on 2022-10-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_contato_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
